"""added default created date

Revision ID: 87251187d2e5
Revises: 6a6b3587d100
Create Date: 2023-08-02 22:37:37.904814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87251187d2e5'
down_revision = '6a6b3587d100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
